apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: secrets-manager-selfsigned
  namespace: secrets-manager-system
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: secrets-manager-webhook-cert
  namespace: secrets-manager-system
  annotations:
    cert-manager.io/alt-names: ""
spec:
  dnsNames:
    - secrets-manager-webhook.secrets-manager-system.svc
    - secrets-manager-webhook.secrets-manager-system.svc.cluster.local
  secretName: secrets-manager-webhook-certs
  issuerRef:
    name: secrets-manager-selfsigned
    kind: Issuer
