apiVersion: v1
kind: Service
metadata:
  name: secrets-manager-webhook
  namespace: secrets-manager-system
spec:
  selector:
    app: secrets-manager-controller
  ports:
    - port: 443
      targetPort: 8443
      name: webhook
