apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-other
  namespace: default
  labels:
    app: other
spec:
  replicas: 1
  selector:
    matchLabels:
      app: other
  template:
    metadata:
      labels:
        app: other
    spec:
      containers:
        - name: app
          image: alpine
          command: ["sleep", "36000"]
