apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-mixed
  namespace: default
  labels:
    app: mixed
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mixed
  template:
    metadata:
      labels:
        app: mixed
    spec:
      containers:
        - name: app
          image: alpine
          command: ["sleep", "36000"]
