apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-multi-container
  namespace: default
  labels:
    app: multi-container
spec:
  replicas: 1
  selector:
    matchLabels:
      app: multi-container
  template:
    metadata:
      labels:
        app: multi-container
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
        - name: sidecar
          image: alpine
          command: ["sleep", "36000"]
