apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-env
  namespace: default
  labels:
    app: env
spec:
  replicas: 1
  selector:
    matchLabels:
      app: env
  template:
    metadata:
      labels:
        app: env
    spec:
      containers:
        - name: app
          image: alpine
          command: ["sleep", "36000"]
