apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-late
  namespace: default
  labels:
    app: late
spec:
  replicas: 1
  selector:
    matchLabels:
      app: late
  template:
    metadata:
      labels:
        app: late
    spec:
      containers:
        - name: app
          image: alpine
          command: ["sleep", "36000"]
