apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: log-agent-ds
  namespace: default
  labels:
    app: log-agent
spec:
  selector:
    matchLabels:
      app: log-agent
  template:
    metadata:
      labels:
        app: log-agent
    spec:
      containers:
        - name: agent
          image: alpine
          command: ["sleep", "36000"]
