apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: secrets-manager-selfsigned
  namespace: { { .Release.Namespace } }
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: secrets-manager-webhook-certs
  namespace: { { .Release.Namespace } }
spec:
  dnsNames:
    - secrets-manager-webhook.{{ .Release.Namespace }}.svc
    - secrets-manager-webhook.{{ .Release.Namespace }}.svc.cluster.local
  secretName: secrets-manager-webhook-certs
  issuerRef:
    name: secrets-manager-selfsigned
    kind: Issuer
