apiVersion: apps/v1
kind: Deployment
metadata:
  name: secrets-manager-controller
  namespace: secrets-manager-system
spec:
  replicas: { { .Values.replicaCount } }
  selector:
    matchLabels:
      app: secrets-manager-controller
  template:
    metadata:
      labels:
        app: secrets-manager-controller
    spec:
      serviceAccountName: secrets-manager-controller-sa
      containers:
        - name: controller
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: { { .Values.image.pullPolicy } }
          args:
            - --webhook
          ports:
            - containerPort: 8443
              name: webhook
              protocol: TCP
          volumeMounts:
            - name: webhook-certs
              mountPath: /etc/webhook/certs
              readOnly: true
      volumes:
        - name: webhook-certs
          secret:
            secretName: secrets-manager-webhook-certs
